// utils/imageHelper.js
const getImagesByGender = (gender) => {
  const path = process.env.REACT_APP_BASE_PATH + '/images/options/';

  const imageSets = {
    Man: [
      ['101_looks_black_suit.jpg', '104_looks_sport_outift.jpg', '107_looks_striped_suit.jpg', '109_looks_beige_pants.jpg', '110_looks_tawb.jpg', '112_looks_casual_suit.jpg', '114_looks_yellow_coat.jpg', '115_looks_dark_blue_suit.jpg', '117_looks_denim_overall.jpg', '121_looks_plaid_shirt.jpg', '122_looks_leaves_pattern_suit.jpg', '125_looks_winter_jacket.jpg', '130_looks_adidas_sweater.jpg', '132_looks_black_outfit.jpg', '133_looks_swimsuit.jpg', '137_looks_blue_sweater.jpg', '139_looks_white_tshirt.jpg', '140_looks_black_casual_tshirt.jpg', '145_looks_wedding_suit.jpg', '147_looks_leather_jacket.jpg'],
      ['200_hair_very_short.jpg', '201_hair_elegant.jpg', '202_hair_bald.jpg', '208_hair_punk.jpg', '209_hair_silver.jpg', '210_hair_black.jpg', '214_hair_chestnut.jpg', '215_hair_curly.jpg', '216_hair_curly_afro.jpg', '217_hair_cowboy.jpg', '219_hair_grey.jpg', '221_hair_long.jpg', '223_hair_short.jpg', '227_hair_brown.jpg', '229_hair_keffiyeh.jpg', '230_hair_pink.jpg', '233_hair_baldness.jpg', '238_hair_blue_strand.jpg', '239_hair_man_bun.jpg', '240_hair_bob.jpg', '242_hair_afro.jpg', '244_hair_shortcut.jpg', '246_hair_retro.jpg', '247_hair_dreadlocks.jpg', '248_hair_strand.jpg', '250_hair_blond.jpg'],
      ['302_footwear_black_loafers.jpg', '303_footwear_white_loafers.jpg', '304_footwear_blue_derbies.jpg', '305_footwear_birkenstocks.jpg', '307_footwear_sports_shoes.jpg', '308_footwear_cowboy_boots.jpg', '311_footwear_barefoot.jpg', '313_footwear_brown_loafers.jpg', '314_footwear_mesh_loafers.jpg', '315_footwear_clapper.jpg', '317_footwear_socks_slippers.jpg', '318_footwear_bicolor_shoes.jpg', '319_footwear_brown_shoes.jpg', '321_footwear_mountain_shoes.jpg', '323_footwear_flip_flops.jpg', '325_footwear_boots.jpg', '329_footwear_beige_loafers.jpg', '331_footwear_brown_leather_shoes.jpg', '332_footwear_red_sneakers.jpg', '333_footwear_sneakers.jpg', '334_footwear_black_leather_shoes.jpg', '335_footwear_brown_boots.jpg', '337_footwear_colored_sneakers.jpg'],
      ['400_transport_city_car.jpg', '401_transport_scooter.jpg', '402_transport_high_speed_train.jpg', '403_transport_city_bike.jpg', '404_transport_red_safari.jpg', '405_transport_skateboard.jpg', '406_transport_family_car_red.jpg', '407_transport_brown_motorboat.jpg', '408_transport_beetle.jpg', '409_transport_family_car.jpg', '410_transport_retro_car.jpg', '411_transport_electric_scooter.jpg', '412_transport_twingo.jpg', '413_transport_red_4x4.jpg', '414_transport_limo.jpg', '415_transport_mini_cooper.jpg', '416_transport_beige_vintage_car.jpg', '417_transport_motorbike.jpg', '418_transport_rolls_royce.jpg', '419_transport_cabriolet.jpg', '420_transport_brown_vintage_car.jpg', '421_transport_fixie_bike.jpg', '422_transport_tesla.jpg', '423_transport_horses.jpg', '424_transport_sports_car.jpg', '425_transport_green_family_car.jpg', '426_transport_double_decker_bus.jpg', '427_transport_blue_truck.jpg'],
      ['501_underwear_dots.jpg', '503_underwear_nude_man.jpg', '506_underwear_white_briefs.jpg', '509_underwear_red.jpg', '513_underwear_mini.jpg', '515_underwear_leo.jpg', '520_underwear_black.jpg', '522_underwear_white_boxers.jpg', '524_underwear_white_black.jpg', '526_underwear_stripped.jpg'],
      ['600_accessories_leather_watch.jpg', '601_accessories_tote.jpg', '602_accessories_book.jpg', '603_accessories_green_sunglasses.jpg', '604_accessories_cuff_bracelet.jpg', '605_accessories_tennis_racket.jpg', '606_accessories_yellow_phone_case.jpg', '607_accessories_sporty_watch.jpg', '608_accessories_vintage_phone.jpg', '609_accessories_whip.jpg', '610_accessories_compass.jpg', '611_accessories_apple_watch.jpg', '612_accessories_snake_ring.jpg', '613_accessories_rock_rings.jpg', '614_accessories_black_gold_watch.jpg', '615_accessories_black_wallet.jpg', '616_accessories_golf_clubs.jpg', '617_accessories_square_watch.jpg', '618_accessories_red_watch.jpg', '619_accessories_black_sunglasses.jpg', '620_accessories_round_watch.jpg', '621_accessories_cord_bracelet.jpg', '622_accessories_turntable.jpg', '623_accessories_silver_cuff_bracelet.jpg', '624_accessories_blue_watch.jpg', '625_accessories_medallion.jpg', '626_accessories_surfing_board.jpg', '627_accessories_silver_metal_bracelet.jpg', '628_accessories_kelly_bag.jpg', '629_accessories_golden_watch.jpg', '630_accessories_brown_sunglasses.jpg', '631_accessories_chanel_watch.jpg', '632_accessories_chanel_bag.jpg', '633_accessories_leo_phone_case.jpg', '634_accessories_pearl_necklace.jpg', '635_accessories_metal_watch.jpg', '636_accessories_blue_phone_case.jpg', '637_accessories_pink_watch.jpg', '638_accessories_green_watch.jpg', '639_accessories_pattern_wallet.jpg', '640_accessories_neon_phone_case.jpg', '641_accessories_chain.jpg', '642_accessories_silver_watch.jpg', '643_accessories_charms.jpg', '644_accessories_bracelet_watch.jpg', '645_accessories_modern_watch.jpg', '646_accessories_bucket_bag.jpg', '647_accessories_black_bracelets.jpg'],
      ['700_environment_provence.jpg','701_environment_date.jpg','702_environment_cocktail.jpg','703_environment_office.jpg','704_environment_mountains.jpg','705_environment_equinox.jpg','706_environment_desert.jpg','707_environment_bedroom.jpg','708_environment_beach.jpg','709_environment_gala.jpg','710_environment_disco.jpg','711_environment_bar.jpg','712_environment_cafe.jpg','713_environment_forest.jpg','714_environment_formal.jpg','715_environment_bed.jpg','716_environment_fireplace.jpg']
    ],
    Woman: [
      ['100_looks_wide_jeans.jpg', '102_looks_sexy_suit.jpg', '103_looks_chanel_suit.jpg', '105_looks_casual_dress.jpg', '106_looks_skinny_dress.jpg', '108_looks_white_gala_dress.jpg', '111_looks_grass_green_dress.jpg', '113_looks_shirtdress.jpg', '116_looks_black_leather.jpg', '118_looks_crop_top.jpg', '119_looks_distressed_jeans.jpg', '120_looks_red_jumpsuit.jpg', '123_looks_casual_flares.jpg', '124_looks_red_gala_dress.jpg', '126_looks_summer_casual.jpg', '127_looks_fuschia_offshoulder.jpg', '128_looks_abaya.jpg', '129_looks_green_gala_dress.jpg', '131_looks_beige_outfit.jpg', '134_looks_black_long_dress.jpg', '135_looks_yellow_dress.jpg', '136_looks_sexy_black_dress.jpg', '138_looks_red_dress.jpg', '141_looks_hijab.jpg', '142_looks_grey_suit.jpg', '143_looks_sport_outfit.jpg', '144_looks_grinding_jeans_suit.jpg', '146_looks_floral_dress.jpg'],
      ['203_hair_voluminous.jpg', '204_hair_blond_bun.jpg', '205_hair_bangs.jpg', '206_hair_long_blond.jpg', '207_hair_black_bun.jpg', '211_hair_short_black.jpg', '212_hair_curly.jpg', '213_hair_short_chestnut.jpg', '218_hair_straight_purple.jpg', '220_hair_mini_blond.jpg', '222_hair_short_afro.jpg', '224_hair_long_chestnut_wavy.jpg', '225_hair_wavy_brown.jpg', '226_hair_short_chestnut.jpg', '228_hair_grey_bun.jpg', '231_hair_red.jpg', '232_hair_mini_brown.jpg', '234_hair_long_parted_black.jpg', '235_hair_long_afro.jpg', '236_hair_white_curly.jpg', '237_hair_short_blond.jpg', '241_hair_short_wavy.jpg', '243_hair_ponytail.jpg', '245_hair_mini_black.jpg', '249_hair_wavy_chestnut.jpg', '251_hair_short_red_afro.jpg'],
      ['300_footwear_heels_boots.jpg', '301_footwear_stilletos.jpg', '303_footwear_white_loafers.jpg', '304_footwear_blue_derbies.jpg', '305_footwear_birkenstocks.jpg', '306_footwear_lace_sandals.jpg', '307_footwear_sports_shoes.jpg', '308_footwear_cowboy_boots.jpg', '309_footwear_yellow_sandles.jpg', '310_footwear_red_stilletos.jpg', '311_footwear_barefoot.jpg', '312_footwear_ballerinas.jpg', '313_footwear_brown_loafers.jpg', '314_footwear_mesh_loafers.jpg', '316_footwear_white_heel_slippers.jpg', '320_footwear_louboutin_heels.jpg', '321_footwear_mountain_shoes.jpg', '322_footwear_pointed_boots.jpg', '323_footwear_flip_flops.jpg', '324_footwear_leather_loafers.jpg', '325_footwear_boots.jpg', '326_footwear_short_heels.jpg', '327_footwear_red_sandals.jpg', '328_footwear_heel_slippers.jpg', '329_footwear_beige_loafers.jpg', '330_footwear_hermes.jpg', '331_footwear_brown_leather_shoes.jpg', '332_footwear_red_sneakers.jpg', '333_footwear_sneakers.jpg', '335_footwear_brown_boots.jpg', '336_footwear_wedge_heels.jpg', '337_footwear_colored_sneakers.jpg', '338_footwear_white_sandles.jpg', '339_footwear_heels_loafers.jpg', '340_footwear_green_slippers.jpg', '341_footwear_high_knees_boots.jpg'],
      ['400_transport_city_car.jpg', '401_transport_scooter.jpg', '402_transport_high_speed_train.jpg', '403_transport_city_bike.jpg', '404_transport_red_safari.jpg', '405_transport_skateboard.jpg', '406_transport_family_car_red.jpg', '407_transport_brown_motorboat.jpg', '408_transport_beetle.jpg', '409_transport_family_car.jpg', '410_transport_retro_car.jpg', '411_transport_electric_scooter.jpg', '412_transport_twingo.jpg', '413_transport_red_4x4.jpg', '414_transport_limo.jpg', '415_transport_mini_cooper.jpg', '416_transport_beige_vintage_car.jpg', '417_transport_motorbike.jpg', '418_transport_rolls_royce.jpg', '419_transport_cabriolet.jpg', '420_transport_brown_vintage_car.jpg', '421_transport_fixie_bike.jpg', '422_transport_tesla.jpg', '423_transport_horses.jpg', '424_transport_sports_car.jpg', '425_transport_green_family_car.jpg', '426_transport_double_decker_bus.jpg', '427_transport_blue_truck.jpg'],
      ['500_underwear_lace_body.jpg', '502_underwear_yellow_pajama.jpg', '504_underwear_white_set.jpg', '505_underwear_blue_bikini.jpg', '507_underwear_bordeaux_set.jpg', '508_underwear_sporty_set.jpg', '510_underwear_lace_set.jpg', '511_underwear_beige_pajama.jpg', '512_underwear_dark_red.jpg', '514_underwear_black_lace_set.jpg', '516_underwear_blue_set.jpg', '517_underwear_nude_woman.jpg', '518_underwear_blue_swimsuit.jpg', '519_underwear_white_lace_set.jpg', '521_underwear_yellow_teddy.jpg', '523_underwear_basic_set.jpg', '525_underwear_white_thong.jpg', '527_underwear_black_silk.jpg'],
      ['600_accessories_leather_watch.jpg', '601_accessories_tote.jpg', '602_accessories_book.jpg', '603_accessories_green_sunglasses.jpg', '604_accessories_cuff_bracelet.jpg', '605_accessories_tennis_racket.jpg', '606_accessories_yellow_phone_case.jpg', '607_accessories_sporty_watch.jpg', '608_accessories_vintage_phone.jpg', '609_accessories_whip.jpg', '610_accessories_compass.jpg', '611_accessories_apple_watch.jpg', '612_accessories_snake_ring.jpg', '613_accessories_rock_rings.jpg', '614_accessories_black_gold_watch.jpg', '615_accessories_black_wallet.jpg', '616_accessories_golf_clubs.jpg', '617_accessories_square_watch.jpg', '618_accessories_red_watch.jpg', '619_accessories_black_sunglasses.jpg', '620_accessories_round_watch.jpg', '621_accessories_cord_bracelet.jpg', '622_accessories_turntable.jpg', '623_accessories_silver_cuff_bracelet.jpg', '624_accessories_blue_watch.jpg', '625_accessories_medallion.jpg', '626_accessories_surfing_board.jpg', '627_accessories_silver_metal_bracelet.jpg', '628_accessories_kelly_bag.jpg', '629_accessories_golden_watch.jpg', '630_accessories_brown_sunglasses.jpg', '631_accessories_chanel_watch.jpg', '632_accessories_chanel_bag.jpg', '633_accessories_leo_phone_case.jpg', '634_accessories_pearl_necklace.jpg', '635_accessories_metal_watch.jpg', '636_accessories_blue_phone_case.jpg', '637_accessories_pink_watch.jpg', '638_accessories_green_watch.jpg', '639_accessories_pattern_wallet.jpg', '640_accessories_neon_phone_case.jpg', '641_accessories_chain.jpg', '642_accessories_silver_watch.jpg', '643_accessories_charms.jpg', '644_accessories_bracelet_watch.jpg', '645_accessories_modern_watch.jpg', '646_accessories_bucket_bag.jpg', '647_accessories_black_bracelets.jpg'],
      ['700_environment_provence.jpg', '701_environment_date.jpg', '702_environment_cocktail.jpg', '703_environment_office.jpg', '704_environment_mountains.jpg', '705_environment_equinox.jpg', '706_environment_desert.jpg', '707_environment_bedroom.jpg', '708_environment_beach.jpg', '709_environment_gala.jpg', '710_environment_disco.jpg', '711_environment_bar.jpg', '712_environment_cafe.jpg', '713_environment_forest.jpg', '714_environment_formal.jpg', '715_environment_bed.jpg', '716_environment_fireplace.jpg']
    ],
    Neutral: [
      ['100_looks_wide_jeans.jpg', '101_looks_black_suit.jpg', '102_looks_sexy_suit.jpg', '103_looks_chanel_suit.jpg', '104_looks_sport_outift.jpg', '105_looks_casual_dress.jpg', '106_looks_skinny_dress.jpg', '107_looks_striped_suit.jpg', '108_looks_white_gala_dress.jpg', '109_looks_beige_pants.jpg', '110_looks_tawb.jpg', '111_looks_grass_green_dress.jpg', '112_looks_casual_suit.jpg', '113_looks_shirtdress.jpg', '114_looks_yellow_coat.jpg', '115_looks_dark_blue_suit.jpg', '116_looks_black_leather.jpg', '117_looks_denim_overall.jpg', '118_looks_crop_top.jpg', '119_looks_distressed_jeans.jpg', '120_looks_red_jumpsuit.jpg', '121_looks_plaid_shirt.jpg', '122_looks_leaves_pattern_suit.jpg', '123_looks_casual_flares.jpg', '124_looks_red_gala_dress.jpg', '125_looks_winter_jacket.jpg', '126_looks_summer_casual.jpg', '127_looks_fuschia_offshoulder.jpg', '128_looks_abaya.jpg', '129_looks_green_gala_dress.jpg', '130_looks_adidas_sweater.jpg', '131_looks_beige_outfit.jpg', '132_looks_black_outfit.jpg', '133_looks_swimsuit.jpg', '134_looks_black_long_dress.jpg', '135_looks_yellow_dress.jpg', '136_looks_sexy_black_dress.jpg', '137_looks_blue_sweater.jpg', '138_looks_red_dress.jpg', '139_looks_white_tshirt.jpg', '140_looks_black_casual_tshirt.jpg', '141_looks_hijab.jpg', '142_looks_grey_suit.jpg', '143_looks_sport_outfit.jpg', '144_looks_grinding_jeans_suit.jpg', '145_looks_wedding_suit.jpg', '146_looks_floral_dress.jpg', '147_looks_leather_jacket.jpg'],
      ['200_hair_very_short.jpg', '201_hair_elegant.jpg', '202_hair_bald.jpg', '203_hair_voluminous.jpg', '204_hair_blond_bun.jpg', '205_hair_bangs.jpg', '206_hair_long_blond.jpg', '207_hair_black_bun.jpg', '208_hair_punk.jpg', '209_hair_silver.jpg', '210_hair_black.jpg', '211_hair_short_black.jpg', '212_hair_curly.jpg', '213_hair_short_chestnut.jpg', '214_hair_chestnut.jpg', '215_hair_curly.jpg', '216_hair_curly_afro.jpg', '217_hair_cowboy.jpg', '218_hair_straight_purple.jpg', '219_hair_grey.jpg', '220_hair_mini_blond.jpg', '221_hair_long.jpg', '222_hair_short_afro.jpg', '223_hair_short.jpg', '224_hair_long_chestnut_wavy.jpg', '225_hair_wavy_brown.jpg', '226_hair_short_chestnut.jpg', '227_hair_brown.jpg', '228_hair_grey_bun.jpg', '229_hair_keffiyeh.jpg', '230_hair_pink.jpg', '231_hair_red.jpg', '232_hair_mini_brown.jpg', '233_hair_baldness.jpg', '234_hair_long_parted_black.jpg', '235_hair_long_afro.jpg', '236_hair_white_curly.jpg', '237_hair_short_blond.jpg', '238_hair_blue_strand.jpg', '239_hair_man_bun.jpg', '240_hair_bob.jpg', '241_hair_short_wavy.jpg', '242_hair_afro.jpg', '243_hair_ponytail.jpg', '244_hair_shortcut.jpg', '245_hair_mini_black.jpg', '246_hair_retro.jpg', '247_hair_dreadlocks.jpg', '248_hair_strand.jpg', '249_hair_wavy_chestnut.jpg', '250_hair_blond.jpg', '251_hair_short_red_afro.jpg'],
      ['300_footwear_heels_boots.jpg', '301_footwear_stilletos.jpg', '302_footwear_black_loafers.jpg', '303_footwear_white_loafers.jpg', '304_footwear_blue_derbies.jpg', '305_footwear_birkenstocks.jpg', '306_footwear_lace_sandals.jpg', '307_footwear_sports_shoes.jpg', '308_footwear_cowboy_boots.jpg', '309_footwear_yellow_sandals.jpg', '310_footwear_red_stilletos.jpg', '311_footwear_barefoot.jpg', '312_footwear_ballerinas.jpg', '313_footwear_brown_loafers.jpg', '314_footwear_mesh_loafers.jpg', '315_footwear_clapper.jpg', '316_footwear_white_heel_slippers.jpg', '317_footwear_socks_slippers.jpg', '318_footwear_bicolor_shoes.jpg', '319_footwear_brown_shoes.jpg', '320_footwear_louboutin_heels.jpg', '321_footwear_mountain_shoes.jpg', '322_footwear_pointed_boots.jpg', '323_footwear_flip_flops.jpg', '324_footwear_leather_loafers.jpg', '325_footwear_boots.jpg', '326_footwear_short_heels.jpg', '327_footwear_red_sandals.jpg', '328_footwear_heel_slippers.jpg', '329_footwear_beige_loafers.jpg', '330_footwear_hermes.jpg', '331_footwear_brown_leather_shoes.jpg', '332_footwear_red_sneakers.jpg', '333_footwear_sneakers.jpg', '334_footwear_black_leather_shoes.jpg', '335_footwear_brown_boots.jpg', '336_footwear_wedge_heels.jpg', '337_footwear_colored_sneakers.jpg', '338_footwear_white_sandles.jpg', '339_footwear_heels_loafers.jpg', '340_footwear_green_slippers.jpg', '341_footwear_high_knees_boots.jpg'],
      ['400_transport_city_car.jpg','401_transport_scooter.jpg','402_transport_high_speed_train.jpg','403_transport_city_bike.jpg','404_transport_red_safari.jpg','405_transport_skateboard.jpg','406_transport_family_car_red.jpg','407_transport_brown_motorboat.jpg','408_transport_beetle.jpg','409_transport_family_car.jpg','410_transport_retro_car.jpg','411_transport_electric_scooter.jpg','412_transport_twingo.jpg','413_transport_red_4x4.jpg','414_transport_limo.jpg','415_transport_mini_cooper.jpg','416_transport_beige_vintage_car.jpg','417_transport_motorbike.jpg','418_transport_rolls_royce.jpg','419_transport_cabriolet.jpg','420_transport_brown_vintage_car.jpg','421_transport_fixie_bike.jpg','422_transport_tesla.jpg','423_transport_horses.jpg','424_transport_sports_car.jpg','425_transport_green_family_car.jpg','426_transport_double_decker_bus.jpg','427_transport_blue_truck.jpg'],
      ['500_underwear_lace_body.jpg', '501_underwear_dots.jpg', '502_underwear_yellow_pajama.jpg', '503_underwear_nude_man.jpg', '504_underwear_white_set.jpg', '505_underwear_blue_bikini.jpg', '506_underwear_white_briefs.jpg', '507_underwear_bordeaux_set.jpg', '508_underwear_sporty_set.jpg', '509_underwear_red.jpg', '510_underwear_lace_set.jpg', '511_underwear_beige_pajama.jpg', '512_underwear_dark_red.jpg', '513_underwear_mini.jpg', '514_underwear_black_lace_set.jpg', '515_underwear_leo.jpg', '516_underwear_blue_set.jpg', '517_underwear_nude_woman.jpg', '518_underwear_blue_swimsuit.jpg', '519_underwear_white_lace_set.jpg', '520_underwear_black.jpg', '521_underwear_yellow_teddy.jpg', '522_underwear_white_boxers.jpg', '523_underwear_basic_set.jpg', '524_underwear_white_black.jpg', '525_underwear_white_thong.jpg', '526_underwear_stripped.jpg', '527_underwear_black_silk.jpg'],
      ['600_accessories_leather_watch.jpg', '601_accessories_tote.jpg', '602_accessories_book.jpg', '603_accessories_green_sunglasses.jpg', '604_accessories_cuff_bracelet.jpg', '605_accessories_tennis_racket.jpg', '606_accessories_yellow_phone_case.jpg', '607_accessories_sporty_watch.jpg', '608_accessories_vintage_phone.jpg', '609_accessories_whip.jpg', '610_accessories_compass.jpg', '611_accessories_apple_watch.jpg', '612_accessories_snake_ring.jpg', '613_accessories_rock_rings.jpg', '614_accessories_black_gold_watch.jpg', '615_accessories_black_wallet.jpg', '616_accessories_golf_clubs.jpg', '617_accessories_square_watch.jpg', '618_accessories_red_watch.jpg', '619_accessories_black_sunglasses.jpg', '620_accessories_round_watch.jpg', '621_accessories_cord_bracelet.jpg', '622_accessories_turntable.jpg', '623_accessories_silver_cuff_bracelet.jpg', '624_accessories_blue_watch.jpg', '625_accessories_medallion.jpg', '626_accessories_surfing_board.jpg', '627_accessories_silver_metal_bracelet.jpg', '628_accessories_kelly_bag.jpg', '629_accessories_golden_watch.jpg', '630_accessories_brown_sunglasses.jpg', '631_accessories_chanel_watch.jpg', '632_accessories_chanel_bag.jpg', '633_accessories_leo_phone_case.jpg', '634_accessories_pearl_necklace.jpg', '635_accessories_metal_watch.jpg', '636_accessories_blue_phone_case.jpg', '637_accessories_pink_watch.jpg', '638_accessories_green_watch.jpg', '639_accessories_pattern_wallet.jpg', '640_accessories_neon_phone_case.jpg', '641_accessories_chain.jpg', '642_accessories_silver_watch.jpg', '643_accessories_charms.jpg', '644_accessories_bracelet_watch.jpg', '645_accessories_modern_watch.jpg', '646_accessories_bucket_bag.jpg', '647_accessories_black_bracelets.jpg'],
      ['700_environment_provence.jpg', '701_environment_date.jpg', '702_environment_cocktail.jpg', '703_environment_office.jpg', '704_environment_mountains.jpg', '705_environment_equinox.jpg', '706_environment_desert.jpg', '707_environment_bedroom.jpg', '708_environment_beach.jpg', '709_environment_gala.jpg', '710_environment_disco.jpg', '711_environment_bar.jpg', '712_environment_cafe.jpg', '713_environment_forest.jpg', '714_environment_formal.jpg', '715_environment_bed.jpg', '716_environment_fireplace.jpg']
    ]
  };

  return Array.from({ length: 7 }, (_, i) => {
    return (imageSets[gender] && imageSets[gender][i] || imageSets['Neutral'][i % imageSets['Neutral'].length])
      .map(img => ({ src: `${path}${img}`, alt: `${gender} Image ${img}` }));
  });
};

export default getImagesByGender;
