// utils/imageHelper.js
const getImagesByGender = (gender) => {
  const path = process.env.REACT_APP_BASE_PATH + 'images/options/';

  const imageSets = {
    Man: [
      ['101_looks_black_suit.jpg', '104_looks_sport_outift.jpg', '107_looks_striped_suit.jpg', '109_looks_beige_pants.jpg', '110_looks_tawb.jpg', '112_looks_casual_suit.jpg', '114_looks_yellow_coat.jpg', '115_looks_dark_blue_suit.jpg', '117_looks_denim_overall.jpg', '121_looks_plaid_shirt.jpg', '122_looks_leaves_pattern_suit.jpg', '125_looks_winter_jacket.jpg', '130_looks_adidas_sweater.jpg', '132_looks_black_outfit.jpg', '133_looks_swimsuit.jpg'],
      ['200_hair_very_short.jpg', '201_hair_elegant.jpg', '202_hair_bald.jpg', '208_hair_punk.jpg', '209_hair_silver.jpg', '210_hair_black.jpg', '214_hair_chestnut.jpg', '215_hair_curly.jpg', '216_hair_curly_afro.jpg', '217_hair_cowboy.jpg', '219_hair_grey.jpg', '221_hair_long.jpg', '223_hair_short.jpg', '227_hair_brown.jpg', '229_hair_keffiyeh.jpg'],
      ['302_footwear_black_loafers.jpg', '303_footwear_white_loafers.jpg', '304_footwear_blue_derbies.jpg', '305_footwear_birkenstocks.jpg', '307_footwear_sports_shoes.jpg', '308_footwear_cowboy_boots.jpg', '311_footwear_barefoot.jpg', '313_footwear_brown_loafers.jpg', '314_footwear_mesh_loafers.jpg', '315_footwear_clapper.jpg', '317_footwear_socks_slippers.jpg', '318_footwear_bicolor_shoes.jpg', '319_footwear_brown_shoes.jpg', '321_footwear_mountain_shoes.jpg', '323_footwear_flip_flops.jpg'],
      ['400_transport_city_car.jpg', '401_transport_scooter.jpg', '402_transport_high_speed_train.jpg', '403_transport_city_bike.jpg', '404_transport_red_safari.jpg', '405_transport_skateboard.jpg', '406_transport_family_car_red.jpg', '407_transport_brown_motorboat.jpg', '408_transport_beetle.jpg', '409_transport_family_car.jpg', '410_transport_retro_car.jpg', '411_transport_electric_scooter.jpg', '412_transport_twingo.jpg', '413_transport_red_4x4.jpg', '414_transport_limo.jpg'],
      ['501_underwear_dots.jpg', '503_underwear_nude_man.jpg', '506_underwear_white_briefs.jpg', '509_underwear_red.jpg', '513_underwear_mini.jpg', '515_underwear_leo.jpg', '520_underwear_black.jpg', '522_underwear_white_boxers.jpg', '524_underwear_white_black.jpg', '526_underwear_stripped.jpg'],
      ['600_accessories_leather_watch.jpg', '601_accessories_tote.jpg', '602_accessories_book.jpg', '603_accessories_green_sunglasses.jpg', '604_accessories_cuff_bracelet.jpg', '605_accessories_tennis_racket.jpg', '606_accessories_yellow_phone_case.jpg', '607_accessories_sporty_watch.jpg', '608_accessories_vintage_phone.jpg', '609_accessories_whip.jpg', '610_accessories_compass.jpg', '611_accessories_apple_watch.jpg', '612_accessories_snake_ring.jpg', '613_accessories_rock_rings.jpg', '614_accessories_black_gold_watch.jpg'],
      ['700_environment_provence.jpg', '701_environment_date.jpg', '702_environment_cocktail.jpg', '703_environment_office.jpg', '704_environment_mountains.jpg', '705_environment_equinox.jpg', '706_environment_desert.jpg', '707_environment_bedroom.jpg', '708_environment_beach.jpg', '709_environment_gala.jpg', '710_environment_disco.jpg', '711_environment_bar.jpg', '712_environment_cafe.jpg', '713_environment_forest.jpg', '714_environment_formal.jpg'],
      ['801_shengxiao_shu.jpg', '802_shengxiao_niu.jpg', '803_shengxiao_hu.jpg', '804_shengxiao_tu.jpg', '805_shengxiao_long.jpg', '806_shengxiao_she.jpg', '807_shengxiao_ma.jpg', '808_shengxiao_yang.jpg', '809_shengxiao_hou.jpg', '810_shengxiao_ji.jpg', '811_shengxiao_gou.jpg', '812_shengxiao_zhu.jpg'],
      ['901_xingzuo_baiyang.jpg', '902_xingzuo_chunv.jpg', '903_xingzuo_jinniu.jpg', '904_xingzuo_juxie.jpg', '905_xingzuo_mojie.jpg', '906_xingzuo_sheshou.jpg', '907_xingzuo_shizi.jpg', '908_xingzuo_shuangyu.jpg', '909_xingzuo_shuangzi.jpg', '910_xingzuo_shuiping.jpg', '911_xingzuo_tiancheng.jpg', '912_xingzuo_tianxie.jpg']
    ],
    Woman: [
      ['100_looks_wide_jeans.jpg', '102_looks_sexy_suit.jpg', '103_looks_chanel_suit.jpg', '105_looks_casual_dress.jpg', '106_looks_skinny_dress.jpg', '108_looks_white_gala_dress.jpg', '111_looks_grass_green_dress.jpg', '113_looks_shirtdress.jpg', '116_looks_black_leather.jpg', '118_looks_crop_top.jpg', '119_looks_distressed_jeans.jpg', '120_looks_red_jumpsuit.jpg', '123_looks_casual_flares.jpg', '124_looks_red_gala_dress.jpg', '126_looks_summer_casual.jpg'],
      ['203_hair_voluminous.jpg', '204_hair_blond_bun.jpg', '205_hair_bangs.jpg', '206_hair_long_blond.jpg', '207_hair_black_bun.jpg', '211_hair_short_black.jpg', '212_hair_curly.jpg', '213_hair_short_chestnut.jpg', '218_hair_straight_purple.jpg', '220_hair_mini_blond.jpg', '222_hair_short_afro.jpg', '224_hair_long_chestnut_wavy.jpg', '225_hair_wavy_brown.jpg', '226_hair_short_chestnut.jpg', '228_hair_grey_bun.jpg'],
      ['300_footwear_heels_boots.jpg', '301_footwear_stilletos.jpg', '303_footwear_white_loafers.jpg', '304_footwear_blue_derbies.jpg', '305_footwear_birkenstocks.jpg', '306_footwear_lace_sandals.jpg', '307_footwear_sports_shoes.jpg', '308_footwear_cowboy_boots.jpg', '309_footwear_yellow_sandles.jpg', '310_footwear_red_stilletos.jpg', '311_footwear_barefoot.jpg', '312_footwear_ballerinas.jpg', '313_footwear_brown_loafers.jpg', '314_footwear_mesh_loafers.jpg', '316_footwear_white_heel_slippers.jpg'],
      ['400_transport_city_car.jpg', '401_transport_scooter.jpg', '402_transport_high_speed_train.jpg', '403_transport_city_bike.jpg', '404_transport_red_safari.jpg', '405_transport_skateboard.jpg', '406_transport_family_car_red.jpg', '407_transport_brown_motorboat.jpg', '408_transport_beetle.jpg', '409_transport_family_car.jpg', '410_transport_retro_car.jpg', '411_transport_electric_scooter.jpg', '412_transport_twingo.jpg', '413_transport_red_4x4.jpg', '414_transport_limo.jpg'],
      ['500_underwear_lace_body.jpg', '502_underwear_yellow_pajama.jpg', '504_underwear_white_set.jpg', '505_underwear_blue_bikini.jpg', '507_underwear_bordeaux_set.jpg', '508_underwear_sporty_set.jpg', '510_underwear_lace_set.jpg', '511_underwear_beige_pajama.jpg', '512_underwear_dark_red.jpg', '514_underwear_black_lace_set.jpg', '516_underwear_blue_set.jpg', '517_underwear_nude_woman.jpg', '518_underwear_blue_swimsuit.jpg', '519_underwear_white_lace_set.jpg', '521_underwear_yellow_teddy.jpg'],
      ['600_accessories_leather_watch.jpg', '601_accessories_tote.jpg', '602_accessories_book.jpg', '603_accessories_green_sunglasses.jpg', '604_accessories_cuff_bracelet.jpg', '605_accessories_tennis_racket.jpg', '606_accessories_yellow_phone_case.jpg', '607_accessories_sporty_watch.jpg', '608_accessories_vintage_phone.jpg', '609_accessories_whip.jpg', '610_accessories_compass.jpg', '611_accessories_apple_watch.jpg', '612_accessories_snake_ring.jpg', '613_accessories_rock_rings.jpg', '614_accessories_black_gold_watch.jpg'],
      ['700_environment_provence.jpg', '701_environment_date.jpg', '702_environment_cocktail.jpg', '703_environment_office.jpg', '704_environment_mountains.jpg', '705_environment_equinox.jpg', '706_environment_desert.jpg', '707_environment_bedroom.jpg', '708_environment_beach.jpg', '709_environment_gala.jpg', '710_environment_disco.jpg', '711_environment_bar.jpg', '712_environment_cafe.jpg', '713_environment_forest.jpg', '714_environment_formal.jpg'],
      ['801_shengxiao_shu.jpg', '802_shengxiao_niu.jpg', '803_shengxiao_hu.jpg', '804_shengxiao_tu.jpg', '805_shengxiao_long.jpg', '806_shengxiao_she.jpg', '807_shengxiao_ma.jpg', '808_shengxiao_yang.jpg', '809_shengxiao_hou.jpg', '810_shengxiao_ji.jpg', '811_shengxiao_gou.jpg', '812_shengxiao_zhu.jpg'],
      ['901_xingzuo_baiyang.jpg', '902_xingzuo_chunv.jpg', '903_xingzuo_jinniu.jpg', '904_xingzuo_juxie.jpg', '905_xingzuo_mojie.jpg', '906_xingzuo_sheshou.jpg', '907_xingzuo_shizi.jpg', '908_xingzuo_shuangyu.jpg', '909_xingzuo_shuangzi.jpg', '910_xingzuo_shuiping.jpg', '911_xingzuo_tiancheng.jpg', '912_xingzuo_tianxie.jpg']
    ],
    Neutral: [
      ['100_looks_wide_jeans.jpg', '101_looks_black_suit.jpg', '102_looks_sexy_suit.jpg', '103_looks_chanel_suit.jpg', '104_looks_sport_outift.jpg', '105_looks_casual_dress.jpg', '106_looks_skinny_dress.jpg', '107_looks_striped_suit.jpg', '108_looks_white_gala_dress.jpg', '109_looks_beige_pants.jpg', '110_looks_tawb.jpg', '111_looks_grass_green_dress.jpg', '112_looks_casual_suit.jpg', '113_looks_shirtdress.jpg', '133_looks_swimsuit.jpg'],
      ['200_hair_very_short.jpg', '201_hair_elegant.jpg', '202_hair_bald.jpg', '203_hair_voluminous.jpg', '204_hair_blond_bun.jpg', '205_hair_bangs.jpg', '206_hair_long_blond.jpg', '207_hair_black_bun.jpg', '208_hair_punk.jpg', '209_hair_silver.jpg', '210_hair_black.jpg', '211_hair_short_black.jpg', '212_hair_curly.jpg', '213_hair_short_chestnut.jpg', '214_hair_chestnut.jpg'],
      ['300_footwear_heels_boots.jpg', '301_footwear_stilletos.jpg', '302_footwear_black_loafers.jpg', '303_footwear_white_loafers.jpg', '304_footwear_blue_derbies.jpg', '305_footwear_birkenstocks.jpg', '306_footwear_lace_sandals.jpg', '307_footwear_sports_shoes.jpg', '308_footwear_cowboy_boots.jpg', '309_footwear_yellow_sandles.jpg', '310_footwear_red_stilletos.jpg', '311_footwear_barefoot.jpg', '312_footwear_ballerinas.jpg', '313_footwear_brown_loafers.jpg', '314_footwear_mesh_loafers.jpg'],
      ['400_transport_city_car.jpg', '401_transport_scooter.jpg', '402_transport_high_speed_train.jpg', '403_transport_city_bike.jpg', '404_transport_red_safari.jpg', '405_transport_skateboard.jpg', '406_transport_family_car_red.jpg', '407_transport_brown_motorboat.jpg', '408_transport_beetle.jpg', '409_transport_family_car.jpg', '410_transport_retro_car.jpg', '411_transport_electric_scooter.jpg', '412_transport_twingo.jpg', '413_transport_red_4x4.jpg', '414_transport_limo.jpg'],
      ['500_underwear_lace_body.jpg', '501_underwear_dots.jpg', '502_underwear_yellow_pajama.jpg', '503_underwear_nude_man.jpg', '504_underwear_white_set.jpg', '505_underwear_blue_bikini.jpg', '506_underwear_white_briefs.jpg', '507_underwear_bordeaux_set.jpg', '508_underwear_sporty_set.jpg', '509_underwear_red.jpg', '510_underwear_lace_set.jpg', '511_underwear_beige_pajama.jpg', '512_underwear_dark_red.jpg', '513_underwear_mini.jpg', '514_underwear_black_lace_set.jpg'],
      ['600_accessories_leather_watch.jpg', '601_accessories_tote.jpg', '602_accessories_book.jpg', '603_accessories_green_sunglasses.jpg', '604_accessories_cuff_bracelet.jpg', '605_accessories_tennis_racket.jpg', '606_accessories_yellow_phone_case.jpg', '607_accessories_sporty_watch.jpg', '608_accessories_vintage_phone.jpg', '609_accessories_whip.jpg', '610_accessories_compass.jpg', '611_accessories_apple_watch.jpg', '612_accessories_snake_ring.jpg', '613_accessories_rock_rings.jpg', '614_accessories_black_gold_watch.jpg'],
      ['700_environment_provence.jpg', '701_environment_date.jpg', '702_environment_cocktail.jpg', '703_environment_office.jpg', '704_environment_mountains.jpg', '705_environment_equinox.jpg', '706_environment_desert.jpg', '707_environment_bedroom.jpg', '708_environment_beach.jpg', '709_environment_gala.jpg', '710_environment_disco.jpg', '711_environment_bar.jpg', '712_environment_cafe.jpg', '713_environment_forest.jpg', '714_environment_formal.jpg'],
      ['801_shengxiao_shu.jpg', '802_shengxiao_niu.jpg', '803_shengxiao_hu.jpg', '804_shengxiao_tu.jpg', '805_shengxiao_long.jpg', '806_shengxiao_she.jpg', '807_shengxiao_ma.jpg', '808_shengxiao_yang.jpg', '809_shengxiao_hou.jpg', '810_shengxiao_ji.jpg', '811_shengxiao_gou.jpg', '812_shengxiao_zhu.jpg'],
      ['901_xingzuo_baiyang.jpg', '902_xingzuo_chunv.jpg', '903_xingzuo_jinniu.jpg', '904_xingzuo_juxie.jpg', '905_xingzuo_mojie.jpg', '906_xingzuo_sheshou.jpg', '907_xingzuo_shizi.jpg', '908_xingzuo_shuangyu.jpg', '909_xingzuo_shuangzi.jpg', '910_xingzuo_shuiping.jpg', '911_xingzuo_tiancheng.jpg', '912_xingzuo_tianxie.jpg']
    ]
  };

  return Array.from({ length: 9 }, (_, i) => {
    return (imageSets[gender] && imageSets[gender][i] || imageSets['Neutral'][i % imageSets['Neutral'].length])
      .map(img => ({ src: `${path}${img}`, alt: `${gender} Image ${img}` }));
  });
};

export default getImagesByGender;
